version: '3.11'

services:
  backend:
    image: code-review
    build:
      context: src
    volumes:
      - ./src:/opt/backend/
      - ./poetry.lock:/opt/poetry.lock
      - ./pyproject.toml:/opt/pyproject.toml
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]